### PR TITLE
Hyperpose model development and training.

### PR DESCRIPTION
**Pull request by Gyx-One**
uniform training and evalution framework,
with 4 model architectures, 7 model backbones and 2 datasets.

### CODE REVIEW

**Comment by ganler** [comment]
@lgarithm The travis-ci seems to be stuck. 

And I think there're some TODOs:

- [ ] Remove the old `train.py`.
- [ ] Format Yixiao's codes.

**Comment by lgarithm** [comment]
`travis-ci` can be removed now.

**Comment by lgarithm** [comment]
ask admin @zsdonghao to force merge?

On 5 Jun 2020, at 1:03 AM, Jiawei Liu <notifications@github.com<mailto:notifications@github.com>> wrote:



@lgarithm<https://github.com/lgarithm> The travis-ci seems to be stuck.

And I think there're some TODOs:

  *    Remove the old train.py.
  *    Format Yixiao's codes.

**Comment by luomai** [comment]
@lgarithm Done.

**Pull request merged**
